alias cd='z'
alias -s nix='$EDITOR'

_select_dir() { fd --hidden -t d . | fzf --preview 'ls -lah {}'; }
_select_file() { fd --hidden -t f . | fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'; }

fcd() {
  local dir
  dir=$(_select_dir)
  [ -n "$dir" ] && cd "$dir"
}
flf() {
  local dir
  dir=$(_select_dir)
  [ -n "$dir" ] && lf "$dir"
}
fnv() {
  local file
  file=$(_select_file)
  [ -n "$file" ] && nvim "$file"
}

ssh-add ~/.ssh/kybe > /dev/null 2>&1
